### ISSUE TITLE
Menu Scene

### ISSUE THREAD

**Issue by jpierre89** [CS3398-Badoons-Ciao/CS3398-Badoons-F2019#83]
Displayed after log-in. 
Menu bar (file->log-out)
Main menu items to display and link navigation:
Courses
To Do List
Options

Note: To Do List Scene/Options Scenes are independent tasks

**Comment by AlexMorman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Menu Scene](https://trello.com/c/qH7pZrTg/16-menu-scene)
