### ISSUE TITLE
To Do List scene - Controller only

### ISSUE THREAD

**Issue by jpierre89** [CS3398-Badoons-Ciao/CS3398-Badoons-F2019#85]
Implement data display, event handling, menu bar.
Depends on completion of To Do List Scene - View only.

**Comment by Bekahexe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [To Do List scene - Controller only](https://trello.com/c/awDBTYyL/25-to-do-list-scene-controller-only)
