### ISSUE TITLE
Menu Bar Help Item

### ISSUE THREAD

**Issue by jpierre89** [CS3398-Badoons-Ciao/CS3398-Badoons-F2019#90]
Links to a pop-up with brief description of how to use scene.
Should have in for Course Overview Scene and and Course Scene.
For example, Course Scene help may describe how 'weight' works and that duplicate categories/assignment names are not allowed.

**Comment by AlexMorman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Menu Bar Help Item](https://trello.com/c/kbin4Qzo/18-menu-bar-help-item)
